### ISSUE TITLE
Now another error pop up with the update "FlexiCubes is not defined!?

### ISSUE THREAD

**Issue by merecesarchviz** [if-ai/ComfyUI-IF_Trellis#10]
hi

the update fixed the other checkpointloader error but now i got a new one! any idea what is?

**Comment by merecesarchviz** [comment]
![erro](https://github.com/user-attachments/assets/c38320ca-ca1b-49bc-9e85-e8fbe2843c0a)

**Comment by merecesarchviz** [comment]
I found the solution to fix this error:

1- git clone --recurse-submodules https://github.com/NVIDIAGameWorks/kaolin C:\tmp\extensions\kaolin
2 - pip install C:\tmp\extensions\kaolin

**Comment by if-ai** [comment]
but that was in the guide right? maybe I forgot the `--recurse-submodules` flag
