### ISSUE TITLE
Suggestion: multiple images from different angles

### ISSUE THREAD

**Issue by marcovth** [if-ai/ComfyUI-IF_Trellis#11]
Just a quick additional reply to https://github.com/if-ai/ComfyUI-IF_Trellis/issues/5 ...

Take a look at this project. It could use some Comfyui nodes ... https://github.com/murphylmf/M-LRM

The above is a project for orthographic views. I have tried to create these views with Flux, but that's difficult.
I would prefer a 3D generator with multiple free-angle images.

![image](https://github.com/user-attachments/assets/85bb78d7-3935-4ebe-a088-45855f11791e)

**Comment by if-ai** [comment]
There is an update coming for TRellis that also do different angle multiview imagees but I might also port this if I have time available

**Comment by SupercaliG** [comment]
> There is an update coming for TRellis that also do different angle multiview imagees but I might also port this if I have time available

Yes please, but I thought thats what the multi image workflow was for?

**Comment by NeoAnthropocene** [comment]
Hey @SupercaliG Thank you for bringing this up.

If you want multiple views with Flux there are some workflows [[1](https://goshnii.gumroad.com/l/FluxCharacterSheet), [2](https://youtu.be/xULxApAPc88), [3](https://youtu.be/Uls_jXy9RuU?si=UP8KDZA7IkToog8d)] that I can suggest you for character creations.

But I prefer to train a Flux lora and then use it to create character turnovers with the same seed and change the T5 prompt.

Also, there is an easy way to create with [MV-adapter](https://github.com/huanngzh/MV-Adapter) but again the quality is not close to Flux.

@if-ai it would be great to have multi-view option for Trellis, no one did that currently this will be the first 🙏
I've given up on [3D Pack](https://github.com/MrForExample/ComfyUI-3D-Pack)'s repo, which is constantly broken with every update. If there is an easier solution, it would be really useful for everyone.

**Comment by if-ai** [comment]
The multi images  should work now I think you need at least two images input as a batch
