### ISSUE TITLE
Suggestion: optimize to run on 8gb VRAM using 0Lento fork

### ISSUE THREAD

**Issue by jurassicjordan** [if-ai/ComfyUI-IF_Trellis#2]
https://github.com/0lento/TRELLIS/
this runs fantastically on my 12gb vram GPU, and word has it can go down to 8. I highly advise incorporating their optimizations so that it can be used more optimally in multi-AI workflows. Thank you

**Comment by if-ai** [comment]
Yes I am looking into it. Thanks

**Comment by jurassicjordan** [comment]
Closing since the PR was merged 
https://github.com/if-ai/ComfyUI-IF_Trellis/pull/1
thank you!
