### ISSUE TITLE
To much for my GTX 1650? hahah... there is no way to run without Flash Attention?

### ISSUE THREAD

**Issue by KillyTheNetTerminal** [if-ai/ComfyUI-IF_Trellis#21]
IF_TrellisImageTo3D
FlashAttention only supports Ampere GPUs or newer.
Exception raised from mha_fwd at C:\Users\diffu\AppData\Local\Temp\pip-install-zd733ysu\flash-attn_9ee01bbcbe904380a44c30780bc46746\csrc\flash_attn\flash_api.cpp:370 (most recent call first):
00007FF8A60983C900007FF8A6098320 c10.dll!c10::Error::Error [<unknown file> @ <unknown line number>]
00007FF8A6096BEA00007FF8A6096B90 c10.dll!c10::detail::torchCheckFail [<unknown file> @ <unknown line number>]
00007FFF1A6F3F5900007FFF1A6E5D10 flash_attn_2_cuda.cp312-win_amd64.pyd!c10::ivalue::Object::operator= [<unknown file> @ <unknown line number>]
00007FFF1A70698000007FFF1A6FD120 flash_attn_2_cuda.cp312-win_amd64.pyd!PyInit_flash_attn_2_cuda [<unknown file> @ <unknown line number>]
00007FFF1A706A9400007FFF1A6FD120 flash_attn_2_cuda.cp312-win_amd64.pyd!PyInit_flash_attn_2_cuda [<unknown file> @ <unknown line number>]
00007FFF1A6EF0AE00007FFF1A6E5D10 flash_attn_2_cuda.cp312-win_amd64.pyd!c10::ivalue::Object::operator= [<unknown file> @ <unknown line number>]
00007FF899EADE8800007FF899EAD7B4 python312.dll!PyUnicode_DecodeUTF7Stateful [<unknown file> @ <unknown line number>]
00007FF899E6EF3200007FF899E6E8B0 python312.dll!PyObject_Vectorcall [<unknown file> @ <unknown line number>]
00007FF899E6E8E500007FF899E6E8B0 python312.dll!PyObject_Vectorcall [<unknown file> @ <unknown line number>]
00007FF899E6FD9B00007FF899E6F510 python312.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FF899E6DF5C00007FF899E6DDE0 python312.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FF899ED42E500007FF899ED41C0 python312.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FF899ED422F00007FF899ED41C0 python312.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FF802D5E15400007FF802D36D90 torch_python.dll!torch::PythonArgParser::raw_parse [<unknown file> @ <unknown line number>]
00007FFF866DCDDC00007FFF866DCC70 torch_cpu.dll!c10::Dispatcher::callBoxed [<unknown file> @ <unknown line number>]
00007FF802B3739B00007FF802B372F0 torch_python.dll!torch::jit::invokeOperatorFromPython [<unknown file> @ <unknown line number>]
00007FF802B340BD00007FF802B33F70 torch_python.dll!torch::jit::_get_operation_for_overload_or_packet [<unknown file> @ <unknown line number>]
00007FF802A99ED000007FF802A87150 torch_python.dll!c10d::PythonOnCompletionHook::PythonOnCompletionHook [<unknown file> @ <unknown line number>]
00007FF802A41E8600007FF8029BB370 torch_python.dll!registerPythonTensorClass [<unknown file> @ <unknown line number>]
00007FF8024FFC7700007FF8024FE500 torch_python.dll!c10::ivalue::Future::devices [<unknown file> @ <unknown line number>]
00007FF899EADE8800007FF899EAD7B4 python312.dll!PyUnicode_DecodeUTF7Stateful [<unknown file> @ <unknown line number>]
00007FF899ED427600007FF899ED41C0 python312.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FF899E736B600007FF899E6F510 python312.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FF899E6DF5C00007FF899E6DDE0 python312.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FF899E4E11F00007FF899E4E034 python312.dll!PyObject_FastCallDictTstate [<unknown file> @ <unknown line number>]
00007FF899F81B1700007FF899F81A98 python312.dll!PyObject_Call_Prepend [<unknown file> @ <unknown line number>]
00007FF899F81A4200007FF899F7C2C4 python312.dll!PyType_GetSlot [<unknown file> @ <unknown line number>]
00007FF899E6EF3200007FF899E6E8B0 python312.dll!PyObject_Vectorcall [<unknown file> @ <unknown line number>]
00007FF899E6E8E500007FF899E6E8B0 python312.dll!PyObject_Vectorcall [<unknown file> @ <unknown line number>]
00007FF899E6FD9B00007FF899E6F510 python312.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FF899E6DF5C00007FF899E6DDE0 python312.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FF899ED42E500007FF899ED41C0 python312.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FF899EB918300007FF899EB90E8 python312.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FF8029917C100007FF80297D480 torch_python.dll!THPPointer<THPStorage>::THPPointer<THPStorage> [<unknown file> @ <unknown line number>]
00007FF899EADEBA00007FF899EAD7B4 python312.dll!PyUnicode_DecodeUTF7Stateful [<unknown file> @ <unknown line number>]
00007FF899ED427600007FF899ED41C0 python312.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FF899E736B600007FF899E6F510 python312.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FF899E6DF5C00007FF899E6DDE0 python312.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FF899E68E7600007FF899E68AB4 python312.dll!PyArg_CheckPositional [<unknown file> @ <unknown line number>]
00007FF899ED42E500007FF899ED41C0 python312.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FF899ED422F00007FF899ED41C0 python312.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FF899E736B600007FF899E6F510 python312.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FF899E6DF5C00007FF899E6DDE0 python312.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FF899E68E7600007FF899E68AB4 python312.dll!PyArg_CheckPositional [<unknown file> @ <unknown line number>]
00007FF899ED42E500007FF899ED41C0 python312.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FF899ED422F00007FF899ED41C0 python312.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FF899E736B600007FF899E6F510 python312.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FF899E6DF5C00007FF899E6DDE0 python312.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FF899E4E0A700007FF899E4E034 python312.dll!PyObject_FastCallDictTstate [<unknown file> @ <unknown line number>]
00007FF899F81B1700007FF899F81A98 python312.dll!PyObject_Call_Prepend [<unknown file> @ <unknown line number>]
00007FF899F81A4200007FF899F7C2C4 python312.dll!PyType_GetSlot [<unknown file> @ <unknown line number>]
00007FF899E6EF3200007FF899E6E8B0 python312.dll!PyObject_Vectorcall [<unknown file> @ <unknown line number>]
00007FF899E6E8E500007FF899E6E8B0 python312.dll!PyObject_Vectorcall [<unknown file> @ <unknown line number>]
00007FF899E6FD9B00007FF899E6F510 python312.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FF899E6DF5C00007FF899E6DDE0 python312.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FF899E68E7600007FF899E68AB4 python312.dll!PyArg_CheckPositional [<unknown file> @ <unknown line number>]
00007FF899ED42E500007FF899ED41C0 python312.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FF899ED422F00007FF899ED41C0 python312.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FF899E736B600007FF899E6F510 python312.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FF899E6DF5C00007FF899E6DDE0 python312.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FF899E68E7600007FF899E68AB4 python312.dll!PyArg_CheckPositional [<unknown file> @ <unknown line number>]
00007FF899ED42E500007FF899ED41C0 python312.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FF899ED422F00007FF899ED41C0 python312.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FF899E736B600007FF899E6F510 python312.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]

**Comment by if-ai** [comment]
I think it can but I have to make the imports optional I haven't reach there yet but I am testing sage attn on the latest version if people find it to work well I will try making all other atnn optional

**Comment by KillyTheNetTerminal** [comment]
I'm sorry, I'm not an expert on the subject, what do these things refer to? What are these methods of care?

**Comment by if-ai** [comment]
Since you said the problem was flash attention I am thinking it might be
possible to run this using other methods
