### ISSUE TITLE
mat1 and mat2 shapes cannot be multiplied (1374x1536 and 1024x2048) error!?

### ISSUE THREAD

**Issue by merecesarchviz** [if-ai/ComfyUI-IF_Trellis#26]
I update it today but now i got this error, any idea how to solve it?

![err3](https://github.com/user-attachments/assets/bc438c59-ce2e-4eb2-94a7-8deccc5fe8a2)

**Comment by if-ai** [comment]
try dinov2 vitl14 reg  as the dino model not sure why this is happening

**Comment by merecesarchviz** [comment]
> try dinov2 vitl14 reg as the dino model not sure why this is happening

yes using it, it goes well and i don't get error. thnks

**Comment by if-ai** [comment]
okay I will close the issue thanks
