### ISSUE TITLE
  File "G:\comfy-\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 106, in _inner_fn     validate_repo_id(arg_value)   File "G:\comfy-\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 160, in validate_repo_id     raise HFValidationError( huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'G:\comfy-\ComfyUI\models\checkpoints\TRELLIS-image-large/ckpts'.

### ISSUE THREAD

**Issue by 1blackbar** [if-ai/ComfyUI-IF_Trellis#3]
stop adding - or -- to foldernames

**Comment by if-ai** [comment]
I don't think the node works on Pythom embeded envs Is not for portable comfy version yet.

**Comment by rodsott** [comment]
yeap, I'm using Portable version and got the same error.. 

huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'X:\AI\ComfyUI_windows_portable\ComfyUI\models\checkpoints\TRELLIS-image-large/ckpts'.

**Comment by if-ai** [comment]
this is because the legnht of the path somehow HF is interpreting it as a repo ID I will ad something to fix it I think it can work on the portable with that sorry

**Comment by if-ai** [comment]
should be fix

**Comment by rodsott** [comment]
First of all, thank you @if-ai for your work! I'm really eager to try it!! I've used 3d-Pack a bit, but it gave a lot of problems with dependencies, and had to clean install the portable comfy a lot of times. I'm gonna test now to see what you fixed.. thanks!!!

**Comment by if-ai** [comment]
okay I will look again

**Comment by rodsott** [comment]
The preview btw is working nicely loading an existing model I generated with 3D Pack

![image](https://github.com/user-attachments/assets/70dc4c78-302c-4543-9562-593948fe8351)

**Comment by rodsott** [comment]
> okay I will look again

complete error is this:

Model path after ensuring existence: X:\AI\ComfyUI_windows_portable\ComfyUI\models\checkpoints\TRELLIS-image-large
Path exists: True
Loading pipeline.json:
Models in pipeline.json:
  sparse_structure_decoder: ckpts/ss_dec_conv3d_16l8_fp16
  sparse_structure_flow_model: ckpts/ss_flow_img_dit_L_16l8_fp16
  slat_decoder_gs: ckpts/slat_dec_gs_swin8_B_64l8gs32_fp16
  slat_decoder_rf: ckpts/slat_dec_rf_swin8_B_64l8r16_fp16
  slat_decoder_mesh: ckpts/slat_dec_mesh_swin8_B_64l8m256c_fp16
  slat_flow_model: ckpts/slat_flow_img_dit_L_64l8p2_fp16
Error loading TRELLIS model: from_pretrained() takes 1 positional argument but 2 were given
!!! Exception during processing !!! from_pretrained() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "X:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "X:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\IF_TrellisCheckpointLoader.py", line 164, in load_model
    pipeline = TrellisImageTo3DPipeline.from_pretrained(str(self.model_path))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\pipelines\trellis_image_to_3d.py", line 58, in from_pretrained
    pipeline = super(TrellisImageTo3DPipeline, TrellisImageTo3DPipeline).from_pretrained(path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\pipelines\base.py", line 41, in from_pretrained
    k: models.from_pretrained(path, v)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: from_pretrained() takes 1 positional argument but 2 were given

**Comment by if-ai** [comment]
ah yes there is a new preview on comfy it works the same maybe I missed a file I uploaded it once more 
![thorium_KJkxd74Y2D](https://github.com/user-attachments/assets/949459fd-2a9a-421a-a76a-3f48de5daa1b)
thanks for the log

**Comment by if-ai** [comment]
I think I found the mistake and fixed it. I am going to close the issue if is still there. open it again please thanks.

**Comment by rodsott** [comment]
Hi! Now the error is different:

**NameError: name 'FlexiCubes' is not defined**

Here`s the full log:

Model path after ensuring existence: X:\AI\ComfyUI_windows_portable\ComfyUI\models\checkpoints\TRELLIS-image-large
Path exists: True
Loading local model: ss_dec_conv3d_16l8_fp16
X:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\models\sparse_structure_vae.py:102: SyntaxWarning: invalid escape sequence '\m'
  """
X:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\models\sparse_structure_vae.py:211: SyntaxWarning: invalid escape sequence '\m'
  """
[SPARSE][CONV] spconv algo: native
Loading local model: ss_flow_img_dit_L_16l8_fp16
[ATTENTION] Using backend: flash_attn
Loading local model: slat_dec_gs_swin8_B_64l8gs32_fp16
Loading local model: slat_dec_rf_swin8_B_64l8r16_fp16
Loading local model: slat_dec_mesh_swin8_B_64l8m256c_fp16
Error loading TRELLIS model: name 'FlexiCubes' is not defined
!!! Exception during processing !!! name 'FlexiCubes' is not defined
Traceback (most recent call last):
  File "X:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "X:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\IF_TrellisCheckpointLoader.py", line 164, in load_model
    pipeline = TrellisImageTo3DPipeline.from_pretrained(str(self.model_path))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\pipelines\trellis_image_to_3d.py", line 58, in from_pretrained
    pipeline = super(TrellisImageTo3DPipeline, TrellisImageTo3DPipeline).from_pretrained(path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\pipelines\base.py", line 41, in from_pretrained
    k: models.from_pretrained(os.path.join(path, v))
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\models\__init__.py", line 69, in from_pretrained
    model = create_model_from_config(config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\models\__init__.py", line 104, in create_model_from_config
    return model_class(**args)
           ^^^^^^^^^^^^^^^^^^^
  File "X:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\models\structured_latent_vae\decoder_mesh.py", line 105, in __init__
    self.mesh_extractor = SparseFeatures2Mesh(res=self.resolution*4, use_color=self.rep_config.get('use_color', False))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\representations\mesh\cube2mesh.py", line 76, in __init__
    self.mesh_extractor = FlexiCubes(device=device)
                          ^^^^^^^^^^
NameError: name 'FlexiCubes' is not defined

**Comment by EightiesPower** [comment]
I'm still getting this error. I'm not using Portable and I have updated the node. Please help, I've spent a whole day setting this up!

Error loading TRELLIS model: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'G:\Comfy_New\ComfyUI\models\checkpoints\TRELLIS-image-large'.
!!! Exception during processing !!! Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'G:\Comfy_New\ComfyUI\models\checkpoints\TRELLIS-image-large'.
Traceback (most recent call last):
  File "G:\Comfy_New\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Comfy_New\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Comfy_New\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "G:\Comfy_New\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Comfy_New\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\IF_TrellisCheckpointLoader.py", line 239, in load_model
    pipeline = TrellisImageTo3DPipeline.from_pretrained(model_path, dinov2_model=dinov2_model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Comfy_New\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\pipelines\trellis_image_to_3d.py", line 66, in from_pretrained
    pipeline = super(TrellisImageTo3DPipeline, TrellisImageTo3DPipeline).from_pretrained(path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Comfy_New\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\pipelines\base.py", line 46, in from_pretrained
    config_file = hf_hub_download(path, "pipeline.json")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\micromamba\envs\envs\ComfyUI\Lib\site-packages\huggingface_hub\utils\_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "G:\micromamba\envs\envs\ComfyUI\Lib\site-packages\huggingface_hub\utils\_validators.py", line 160, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'G:\Comfy_New\ComfyUI\models\checkpoints\TRELLIS-image-large'.

**Comment by EightiesPower** [comment]
Did that, thank you. Now I'm getting a "pop from empty list" error. I'll start a new issue for that.
