### ISSUE TITLE
facebookresearch/dinov2 can download?

### ISSUE THREAD

**Issue by blueroutecn** [if-ai/ComfyUI-IF_Trellis#30]
I want know where can download it.

**Comment by blueroutecn** [comment]
wget https://dl.fbaipublicfiles.com/dinov2/dinov2_vitl14/dinov2_vitl14_reg4_pretrain.pth -O  /home/llm/linda/lab2/models/classifiers/dinov2_vitl14_reg.pth

I  downloaded pth file, and run error:
      [ATTENTION] Set backend to: sage
      Environment configured - Backend: spconv, Attention: sage, Smooth K: True, SpConv Algo: implicit_gemm
      [ATTENTION] Set backend to: sage
      Loading local model: ss_dec_conv3d_16l8_fp16
      Loading local model: ss_flow_img_dit_L_16l8_fp16
      Loading local model: slat_dec_gs_swin8_B_64l8gs32_fp16
      Loading local model: slat_dec_rf_swin8_B_64l8r16_fp16
      Loading local model: slat_dec_mesh_swin8_B_64l8m256c_fp16
      Loading local model: slat_flow_img_dit_L_64l8p2_fp16
      Loading DINOv2 model from /home/llm/linda/lab2/models/classifiers/dinov2_vitl14_reg.pth
      Error loading TRELLIS model: name 'logger' is not defined
      !!! Exception during processing !!! name 'logger' is not defined

**Comment by if-ai** [comment]
I added the logger should be okay now 

I think it should download correctly now but if it doesnt
You could try downloading the models and place them like this

```
PS D:\ComfyUI\models\checkpoints\TRELLIS-image-large>
│   .gitattributes
│   pipeline.json
│   README.md
└───ckpts
        slat_dec_gs_swin8_B_64l8gs32_fp16.json
        slat_dec_gs_swin8_B_64l8gs32_fp16.safetensors
        slat_dec_mesh_swin8_B_64l8m256c_fp16.json
        slat_dec_mesh_swin8_B_64l8m256c_fp16.safetensors
        slat_dec_rf_swin8_B_64l8r16_fp16.json
        slat_dec_rf_swin8_B_64l8r16_fp16.safetensors
        slat_enc_swin8_B_64l8_fp16.json
        slat_enc_swin8_B_64l8_fp16.safetensors
        slat_flow_img_dit_L_64l8p2_fp16.json
        slat_flow_img_dit_L_64l8p2_fp16.safetensors
        ss_dec_conv3d_16l8_fp16.json
        ss_dec_conv3d_16l8_fp16.safetensors
        ss_enc_conv3d_16l8_fp16.json
        ss_enc_conv3d_16l8_fp16.safetensors
        ss_flow_img_dit_L_16l8_fp16.json
        ss_flow_img_dit_L_16l8_fp16.safetensors

PS D:\ComfyUI\models\classifiers> 
    dinov2_vitl14_reg.pth
```
[trellis](https://huggingface.co/JeffreyXiang/TRELLIS-image-large)
[DinoV2](https://dl.fbaipublicfiles.com/dinov2/dinov2_vitl14/dinov2_vitl14_reg4_pretrain.pth)

You could try downloading manually or I also have a HF downloader for comfy but the Dino needs to be manually downloaded
https://github.com/if-ai/ComfyUI-IF_AI_HFDownloaderNode

**Comment by yorgyetson** [comment]
Looks like the logger is also missing on the trellis_image_to_3d.py pipeline

https://github.com/if-ai/ComfyUI-IF_Trellis/blob/main/trellis/pipelines/trellis_image_to_3d.py
