### ISSUE TITLE
Suggestion: multiple images ftom different angles

### ISSUE THREAD

**Issue by NeoAnthropocene** [if-ai/ComfyUI-IF_Trellis#5]
Is there any ways to feed the model with multiple angle images?

**Comment by if-ai** [comment]
right now the model does this internally there is a nviews parameter but they are all made from guess generations the model make itself.
A manual workround would be create a model from the different angles of the charactre sheet and the merge them all into one. I can apteempt to create an automatic way of doing it via node but this is not priority yet.
