### ISSUE TITLE
Error CheckpointLoader!?

### ISSUE THREAD

**Issue by merecesarchviz** [if-ai/ComfyUI-IF_Trellis#7]
Hi,

I install all well but when i try to generate i got this error! any idea how to solve it?

![erry](https://github.com/user-attachments/assets/bfa55a5f-f508-4c96-9390-098b46ef4337)

**Comment by merecesarchviz** [comment]
any idea how to solve this?

**Comment by if-ai** [comment]
fixed on the last update
